Add trash interaction 2
hahnprojects/flow pull request #122
Opened 2022-07-06 11:36 UTC by jana-wdm

* Add mixins to combine generalized service classes to get mixed services with all methods that are needed.
* Intention: Reduce redundant code

* TODO/WIP: discuss how to solve that in a better way

2022-07-06 12:08 UTC, 3fd requested changes

2022-07-06 12:08 UTC, 3fd commented on package.json
>    }
müsstest das bitte noch mal entfernen und dann unter `packages/api` mit `pnpm i ts-mixer` installieren

2022-07-06 12:08 UTC, 3fd commented on packages/api/MIXINS.md
> +Da wir generische Klassen miteinander mixen sieht unsere Struktur wie folgt aus:
english please

2022-07-12 18:14 UTC, 3fd approved these changes

2022-07-12 18:47 UTC, timoklingenhoefer approved these changes

2022-07-12 18:47 UTC, merged